package com.mitchell.esparza.safe_travels.models;

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.springframework.format.annotation.DateTimeFormat;
import java.util.Objects;


@Entity
@Table(name="expenses")
public class Travel {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Size(min = 5, message="The expense's name must be at least 5 characters long.")
    private String name;

    @NotNull
    @Size(min = 3, message="The vendor's name must be at least 3 characters long.")
    private String vendor;

    @NotNull
    @DecimalMin(value = "0.01", message = "The expense's amount must be at least 0.01.")
    private BigDecimal amount;


    @NotNull
    @Size(min = 5, message="The description must be at least 5 characters long.")
    @Column(columnDefinition = "TEXT") //making sure this column is of type TEXT instead of VARCHAR(255)
    private String description;

    //This will not allow the createdAt column to be updated after creation
    @Column(updatable=false)
    @DateTimeFormat(pattern="yyyy-MM-dd") // @DateTimeFormat annotation tells Hibernate to format the date in the specified pattern
    private Date createdAt;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date updatedAt;

    public Travel() {
        //empty constructor will be used to create an instance of the Travel class that will be used to create a row in the expenses table
    }

    public Travel(String name, String vendor, BigDecimal amount, String description) {
        //this.id = id; will be automatically generated by Hibernate and applied to the instance of the Travel class that we create 
        //same with this.createdAt and this.updatedAt 
        this.name = name;  
        this.vendor = vendor;
        this.amount = amount;
        this.description = description;
    }

    //getters and setters
    @PrePersist
    protected void onCreate(){
        this.createdAt = new Date();
    }
    @PreUpdate
    protected void onUpdate(){
        this.updatedAt = new Date();
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVendor() {
        return this.vendor;
    }

    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}

